# Generated by Django 5.1.2 on 2024-11-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_loginattempt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
