name: Django CI/CD

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/development.txt
    
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: core.settings.development
        DB_NAME: test_db
        DB_USER: root
        DB_PASSWORD: root
        DB_HOST: 127.0.0.1
      run: |
        python manage.py test
        coverage run manage.py test
        coverage report
    
    - name: Run Linting
      run: |
        flake8 .
        black . --check
        isort . --check-only

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Production
      run: |
        echo "Deploy steps here"